#!/bin/bash

# ANSI color reset
reset='\033[0m'

ascii="
   _____ __  __ _______ _____    _______                   
  / ____|  \/  |__   __|  __ \  |__   __|                  
 | (___ | \  / |  | |  | |  | |    | | ___  __ _ _ __ ___  
  \___ \| |\/| |  | |  | |  | |    | |/ _ \/ _` | '_ ` _ \ 
  ____) | |  | |  | |  | |__| |    | |  __/ (_| | | | | | |
 |_____/|_|  |_|  |_|  |_____/     |_|\___|\__,_|_| |_| |_|
"

# List of colors
colors=(31 32 33 34 35 36 91 92 93 94 95 96)

for ((i=0; i<${#ascii}; i++)); do
  char="${ascii:$i:1}"
  if [[ "$char" == " " || "$char" == $'\n' ]]; then
    echo -ne "$char"
  else
    color=${colors[$RANDOM % ${#colors[@]}]}
    echo -ne "\033[0;${color}m${char}${reset}"
  fi
done

echo ""
